services:
  - type: web
    name: rag-bot-backend
    env: python
    region: oregon
    branch: main
    plan: starter

    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"

    envVars:
      - key: GROQ_API_KEY
        sync: false

    autoDeploy: true

    healthCheckPath: /health
